
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Crypto Zombies',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-900 text-slate-200 flex min-h-screen flex-col mx-auto`}>
        <Providers>
          <Header />
          <main className="min-h-screen flex flex-col justify-center items-center text-center">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
